/* global firebase, XLSX, firebaseConfig */
"use strict";
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(), db=firebase.firestore();
let currentUser=null,currentProfile=null,students=[],lastRows=[],charts={};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const isAdmin=()=>currentProfile?.role==="admin";
const fmtDate=d=>d?d.toLocaleString("ru-RU",{dateStyle:"short",timeStyle:"short"}):"";
async function login(){try{await auth.signInWithEmailAndPassword($("loginEmail").value.trim(),$("loginPassword").value)}catch(e){$("loginStatus").textContent="Неверный email или пароль.";$("loginStatus").className="error"}}
async function logout(){await auth.signOut()}
auth.onAuthStateChanged(async user=>{currentUser=user;if(!user){$("loginScreen").classList.remove("hidden");$("app").classList.add("hidden");return}try{const p=await db.collection("users").doc(user.uid).get();if(!p.exists||!["admin","duty"].includes(p.data().role)){await auth.signOut();$("loginStatus").textContent="Нет назначенной роли.";return}currentProfile=p.data();$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");$("userInfo").textContent=`${user.email} · ${isAdmin()?"Администратор":"Дежурный"}`;$("btnAdmin").classList.toggle("hidden",!isAdmin());await loadStudents();await refreshDashboard();await loadToday();await fillClasses();}catch(e){console.error(e);await auth.signOut()}});
function switchTab(name){if(name==="admin"&&!isAdmin())return;document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));$("tab"+name[0].toUpperCase()+name.slice(1)).classList.add("active");$("btn"+name[0].toUpperCase()+name.slice(1)).classList.add("active");if(name==="dashboard")refreshDashboard();if(name==="duty")loadToday();if(name==="journal")loadJournal();if(name==="students")loadStudentDirectory();}
async function loadStudents(){students=[];$("studentsList").innerHTML="";const s=await db.collection("students").orderBy("name").get();s.forEach(d=>{const x={id:d.id,...d.data()};if(x.name&&x.grade){students.push(x);const o=document.createElement("option");o.value=`${x.name} (${x.grade})`;$("studentsList").appendChild(o)}})}
function handleStudentSelect(){const s=students.find(x=>`${x.name} (${x.grade})`===$("studentInput").value.trim());$("studentClass").value=s?s.grade:""}
async function submitRecord(){const s=students.find(x=>`${x.name} (${x.grade})`===$("studentInput").value.trim());if(!s){alert("Выберите ученика из списка.");return}try{const now=new Date();await db.collection("attendance").add({studentId:s.id,studentName:s.name,grade:s.grade,status:$("statusType").value,note:$("recordNote").value.trim(),timestamp:firebase.firestore.Timestamp.fromDate(now),dateStr:dateKey(now),createdBy:currentUser.uid});$("studentInput").value="";$("studentClass").value="";$("recordNote").value="";await loadToday();await refreshDashboard();}catch(e){console.error(e);alert("Ошибка сохранения.")}}
function rowHtml(d,id,actions=true){const dt=d.timestamp?.toDate?.();const st=d.status==="Опоздал"?"late":"absent";return `<tr><td>${esc(fmtDate(dt))}</td><td>${esc(d.studentName)}</td><td>${esc(d.grade)}</td><td><span class="badge ${st}">${esc(d.status)}</span></td><td>${esc(d.note||"-")}</td>${actions?`<td><button class="danger small" onclick="deleteRecord('${esc(id)}')">Удалить</button></td>`:""}</tr>`}
async function loadToday(){try{const snap=await db.collection("attendance").where("dateStr","==",dateKey()).orderBy("timestamp","desc").get();$("todayTable").innerHTML="";snap.forEach(d=>$("todayTable").insertAdjacentHTML("beforeend",rowHtml(d.data(),d.id,isAdmin())));if(!snap.size)$("todayTable").innerHTML='<tr><td colspan="6">Сегодня записей нет.</td></tr>'}catch(e){console.error(e);$("todayTable").innerHTML='<tr><td colspan="6" class="error">Не удалось загрузить записи. Проверьте индекс Firestore.</td></tr>'}}
async function deleteRecord(id){if(!isAdmin()){alert("Удалять записи может только администратор.");return}if(!confirm("Удалить эту запись?"))return;try{await db.collection("attendance").doc(id).delete();await loadToday();await refreshDashboard();await loadJournal();}catch(e){alert("Не удалось удалить запись.")}}
function startDate(period){const d=new Date();if(period==="day")d.setHours(0,0,0,0);if(period==="week")d.setDate(d.getDate()-7);if(period==="month")d.setDate(d.getDate()-30);if(period==="quarter")d.setDate(d.getDate()-90);return d}
async function queryAttendance(period){return db.collection("attendance").where("timestamp",">=",firebase.firestore.Timestamp.fromDate(startDate(period))).orderBy("timestamp","desc").get()}
function aggregate(rows){const byClass={},byStatus={Опоздал:0,Отсутствует:0};rows.forEach(x=>{byClass[x.grade]=(byClass[x.grade]||0)+1;if(byStatus[x.status]!==undefined)byStatus[x.status]++});return {byClass,byStatus}}
function drawCharts(rows){const {byClass,byStatus}=aggregate(rows);if(charts.class)charts.class.destroy();if(charts.status)charts.status.destroy();charts.class=new Chart($("classChart"),{type:"bar",data:{labels:Object.keys(byClass).sort(),datasets:[{label:"Записи",data:Object.keys(byClass).sort().map(k=>byClass[k])}]},options:{responsive:true,plugins:{legend:{display:false}}}});charts.status=new Chart($("statusChart"),{type:"doughnut",data:{labels:Object.keys(byStatus),datasets:[{data:Object.values(byStatus)}]},options:{responsive:true}})}
async function refreshDashboard(){try{const snap=await db.collection("attendance").where("dateStr","==",dateKey()).get();let late=0,abs=0,classes=new Set(),rows=[];snap.forEach(d=>{const x=d.data();x._id=d.id;rows.push(x);classes.add(x.grade);if(x.status==="Опоздал")late++;if(x.status==="Отсутствует")abs++});$("statTotal").textContent=rows.length;$("statLate").textContent=late;$("statAbsent").textContent=abs;$("statClasses").textContent=classes.size;rows.sort((a,b)=>(b.timestamp?.seconds||0)-(a.timestamp?.seconds||0));$("dashboardTable").innerHTML=rows.slice(0,10).map(x=>`<tr><td>${esc(x.timestamp?.toDate().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})||"")}</td><td>${esc(x.studentName)}</td><td>${esc(x.grade)}</td><td><span class="badge ${x.status==="Опоздал"?"late":"absent"}">${esc(x.status)}</span></td></tr>`).join("")||'<tr><td colspan="4">Сегодня записей нет.</td></tr>';drawCharts(rows)}catch(e){console.error(e)}}
async function fillClasses(){const set=new Set(students.map(x=>x.grade));$("classFilter").innerHTML='<option value="">Все классы</option>'+[...set].sort().map(x=>`<option>${esc(x)}</option>`).join("")}
async function loadJournal(){try{const snap=await queryAttendance($("journalPeriod").value),cls=$("classFilter").value,st=$("statusFilter").value;lastRows=[];$("journalTable").innerHTML="";snap.forEach(d=>{const x=d.data();if(cls&&x.grade!==cls)return;if(st&&x.status!==st)return;x._id=d.id;lastRows.push(x);$("journalTable").insertAdjacentHTML("beforeend",rowHtml(x,d.id,isAdmin()))});if(!lastRows.length)$("journalTable").innerHTML='<tr><td colspan="6">Записей нет.</td></tr>'}catch(e){console.error(e);$("journalTable").innerHTML='<tr><td colspan="6" class="error">Ошибка загрузки журнала. Возможно, нужен индекс Firestore.</td></tr>'}}
function rowsForExport(rows){return rows.map(x=>({"Дата":fmtDate(x.timestamp?.toDate?.()),"ФИО":x.studentName||"","Класс":x.grade||"","Статус":x.status||"","Примечание":x.note||""}))}
function exportJournal(){if(!lastRows.length){alert("Сначала сформируйте журнал.");return}downloadXlsx(rowsForExport(lastRows),`журнал-${dateKey()}.xlsx`)}
async function generateReport(){try{const snap=await queryAttendance($("reportPeriod").value);lastRows=[];$("reportTable").innerHTML="";snap.forEach(d=>{const x=d.data();lastRows.push(x);$("reportTable").insertAdjacentHTML("beforeend",`<tr><td>${esc(fmtDate(x.timestamp?.toDate?.()))}</td><td>${esc(x.studentName)}</td><td>${esc(x.grade)}</td><td>${esc(x.status)}</td><td>${esc(x.note||"-")}</td></tr>`)});if(!lastRows.length)$("reportTable").innerHTML='<tr><td colspan="5">Записей нет.</td></tr>'}catch(e){alert("Не удалось сформировать отчет. Возможно, нужен индекс Firestore.")}}
function exportReport(){if(!lastRows.length){alert("Сначала сформируйте отчет.");return}downloadXlsx(rowsForExport(lastRows),`отчет-${dateKey()}.xlsx`)}
function downloadXlsx(rows,name){const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Посещаемость");XLSX.writeFile(wb,name)}
async function uploadExcel(){if(!isAdmin())return;const file=$("excelFile").files[0];if(!file){alert("Выберите Excel.");return}const reader=new FileReader();reader.onload=async e=>{try{const wb=XLSX.read(new Uint8Array(e.target.result),{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});const incoming=rows.map(r=>({name:String(r["ФИО"]||r.Name||r.FIO||"").trim(),grade:String(r["Класс"]||r.Grade||"").trim()})).filter(x=>x.name&&x.grade);const existing=await db.collection("students").get(),map=new Map();existing.forEach(d=>{const x=d.data();map.set(`${x.name}|${x.grade}`,d.ref)});let n=0;for(let i=0;i<incoming.length;i+=450){const b=db.batch();incoming.slice(i,i+450).forEach(x=>{const ref=map.get(`${x.name}|${x.grade}`)||db.collection("students").doc();b.set(ref,x,{merge:true});n++});await b.commit();$("importStatus").textContent=`Обработано ${n}/${incoming.length}`}await loadStudents();await fillClasses();await loadStudentDirectory();$("importStatus").className="successText"}catch(err){console.error(err);$("importStatus").textContent="Ошибка импорта.";$("importStatus").className="error"}};reader.readAsArrayBuffer(file)}
async function loadStudentDirectory(){const q=$("studentSearch")?.value.trim().toLowerCase()||"",cls=$("studentClassFilter")?.value||"";const list=students.filter(s=>(!q||s.name.toLowerCase().includes(q))&&(!cls||s.grade===cls));$("studentCount").textContent=list.length;$("studentDirectory").innerHTML=list.map(s=>`<tr><td><button class="link" onclick="openStudent('${esc(s.id)}')">${esc(s.name)}</button></td><td>${esc(s.grade)}</td></tr>`).join("")||'<tr><td colspan="2">Ученики не найдены.</td></tr>'}
function fillStudentClasses(){const set=new Set(students.map(x=>x.grade));$("studentClassFilter").innerHTML='<option value="">Все классы</option>'+[...set].sort().map(x=>`<option>${esc(x)}</option>`).join("")}
async function openStudent(id){const s=students.find(x=>x.id===id);if(!s)return;switchTab("students");$("studentProfile").classList.remove("hidden");$("profileName").textContent=s.name;$("profileClass").textContent=s.grade;const snap=await db.collection("attendance").where("studentId","==",id).orderBy("timestamp","desc").limit(200).get();let late=0,abs=0,rows=[];snap.forEach(d=>{const x=d.data();rows.push(x);if(x.status==="Опоздал")late++;if(x.status==="Отсутствует")abs++});$("profileTotal").textContent=rows.length;$("profileLate").textContent=late;$("profileAbsent").textContent=abs;$("profileRate").textContent=rows.length?`${Math.round((abs+late)/rows.length*100)}%`:"—";$("profileTable").innerHTML=rows.map(x=>`<tr><td>${esc(fmtDate(x.timestamp?.toDate?.()))}</td><td><span class="badge ${x.status==="Опоздал"?"late":"absent"}">${esc(x.status)}</span></td><td>${esc(x.note||"-")}</td></tr>`).join("")||'<tr><td colspan="3">Истории нет.</td></tr>'}
function closeStudent(){$("studentProfile").classList.add("hidden")}
